/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jhont
 */
public class vistaActualizarPrecioDeVenta extends javax.swing.JFrame {

    /**
     * Creates new form vistaActualizarPrecioDeVenta
     */
    public vistaActualizarPrecioDeVenta() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        txtPrecioActual = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtModificacion = new javax.swing.JTextField();
        BotonActualizar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Actualizar_Precio_De_Venta");

        jLabel11.setText("Precio de venta actual:");

        txtPrecioActual.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecioActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActualActionPerformed(evt);
            }
        });

        jLabel12.setText("Nuevo precio de venta:");

        txtModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificacionActionPerformed(evt);
            }
        });

        BotonActualizar.setText("Actualizar");

        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(49, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BotonCancelar)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                        .createSequentialGroup()
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel12)
                                                                .addComponent(jLabel11))
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(txtPrecioActual)
                                                                .addComponent(txtModificacion,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 123,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(74, 74, 74)
                                                        .addComponent(BotonActualizar)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(31, 31, 31)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(txtPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(txtModificacion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18,
                                        Short.MAX_VALUE)
                                .addComponent(BotonCancelar)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioActualActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPrecioActualActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPrecioActualActionPerformed

    private void txtModificacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtModificacionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtModificacionActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BotonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarPrecioDeVenta.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarPrecioDeVenta.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarPrecioDeVenta.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarPrecioDeVenta.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaActualizarPrecioDeVenta().setVisible(true);
            }
        });
    }

    public JButton getBotonActualizar() {
        return BotonActualizar;
    }

    public void setBotonActualizar(JButton BotonActualizar) {
        this.BotonActualizar = BotonActualizar;
    }

    public JButton getBotonCancelar() {
        return BotonCancelar;
    }

    public void setBotonCancelar(JButton BotonCancelar) {
        this.BotonCancelar = BotonCancelar;
    }

    public JTextField getTxtModificacion() {
        return txtModificacion;
    }

    public void setTxtModificacion(JTextField txtModificacion) {
        this.txtModificacion = txtModificacion;
    }

    public JTextField getTxtPrecioActual() {
        return txtPrecioActual;
    }

    public void setTxtPrecioActual(JTextField txtPrecioActual) {
        this.txtPrecioActual = txtPrecioActual;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JTextField txtModificacion;
    private javax.swing.JTextField txtPrecioActual;
    // End of variables declaration//GEN-END:variables
}
