/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jhont
 */
public class vistaActualizarExistencias extends javax.swing.JFrame {

    /**
     * Creates new form vistaActualizarExistencias
     */
    public vistaActualizarExistencias() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        txtModificacion = new javax.swing.JTextField();
        BotonAgregar = new javax.swing.JButton();
        BotonRetirar = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtExistenciasA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Actualizar_Existencias");

        jLabel14.setText("Modificación");

        txtModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificacionActionPerformed(evt);
            }
        });

        BotonAgregar.setText("Agregar");

        BotonRetirar.setText("Retirar");

        BotonRegresar.setText("Regresar");

        jLabel13.setText("Existencias actuales:");

        txtExistenciasA.setBackground(new java.awt.Color(204, 204, 204));
        txtExistenciasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExistenciasAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtModificacion)
                                        .addComponent(txtExistenciasA, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonRegresar)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(BotonAgregar)
                                .addGap(39, 39, 39)
                                .addComponent(BotonRetirar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(txtExistenciasA, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(txtModificacion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonAgregar)
                                        .addComponent(BotonRetirar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16,
                                        Short.MAX_VALUE)
                                .addComponent(BotonRegresar)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModificacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtModificacionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtModificacionActionPerformed

    private void txtExistenciasAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtExistenciasAActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtExistenciasAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarExistencias.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarExistencias.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarExistencias.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarExistencias.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaActualizarExistencias().setVisible(true);
            }
        });
    }

    public JButton getBotonAgregar() {
        return BotonAgregar;
    }

    public void setBotonAgregar(JButton BotonAgregar) {
        this.BotonAgregar = BotonAgregar;
    }

    public JButton getBotonRegresar() {
        return BotonRegresar;
    }

    public void setBotonRegresar(JButton BotonRegresar) {
        this.BotonRegresar = BotonRegresar;
    }

    public JButton getBotonRetirar() {
        return BotonRetirar;
    }

    public void setBotonRetirar(JButton BotonRetirar) {
        this.BotonRetirar = BotonRetirar;
    }

    public JTextField getTxtExistenciasA() {
        return txtExistenciasA;
    }

    public void setTxtExistenciasA(JTextField txtExistenciasA) {
        this.txtExistenciasA = txtExistenciasA;
    }

    public JTextField getTxtModificacion() {
        return txtModificacion;
    }

    public void setTxtModificacion(JTextField txtModificacion) {
        this.txtModificacion = txtModificacion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JButton BotonRetirar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JTextField txtExistenciasA;
    private javax.swing.JTextField txtModificacion;
    // End of variables declaration//GEN-END:variables
}
