/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author jhont
 */
public class vistaBuscadorInventario extends javax.swing.JFrame {

    /**
     * Creates new form vistaBuscadorInventario
     */
    public vistaBuscadorInventario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public JTextArea getTextoDescripcionProducto() {
        return textoDescripcionProducto;
    }

    public void setTextoDescripcionProducto(JTextArea textoDescripcionProducto) {
        this.textoDescripcionProducto = textoDescripcionProducto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextoCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextoProducto = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextoArea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextoClasificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextoCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextoVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextoExistencias = new javax.swing.JTextField();
        TextoCodigoProducto = new javax.swing.JTextField();
        TextoCodigoArea = new javax.swing.JTextField();
        TextoCodigoClasificacion = new javax.swing.JTextField();
        BotonActualizarPrecioDeLaCompra = new javax.swing.JButton();
        BotonActualizarPrecioDeVenta = new javax.swing.JButton();
        BotonActualizarExistencias = new javax.swing.JButton();
        BotonEliminarProductoDelInventario = new javax.swing.JButton();
        BotonRegresarAPantallaPrincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDescripcionProducto = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Busqueda_De_Productos");

        jLabel1.setText("Codigo:");

        jLabel2.setText("Producto:");

        BotonBuscar.setText("Buscar");

        jLabel3.setText("Área:");

        TextoArea.setBackground(new java.awt.Color(204, 204, 204));
        TextoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoAreaActionPerformed(evt);
            }
        });

        jLabel4.setText("Clasificación:");

        TextoClasificacion.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("Compra:");

        TextoCompra.setBackground(new java.awt.Color(204, 204, 204));
        TextoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCompraActionPerformed(evt);
            }
        });

        jLabel6.setText("Venta:");

        TextoVenta.setBackground(new java.awt.Color(204, 204, 204));
        TextoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoVentaActionPerformed(evt);
            }
        });

        jLabel7.setText("Precios:");

        jLabel8.setText("Existencias:");

        TextoExistencias.setBackground(new java.awt.Color(204, 204, 204));
        TextoExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoExistenciasActionPerformed(evt);
            }
        });

        TextoCodigoProducto.setBackground(new java.awt.Color(204, 204, 204));
        TextoCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCodigoProductoActionPerformed(evt);
            }
        });

        TextoCodigoArea.setBackground(new java.awt.Color(204, 204, 204));
        TextoCodigoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCodigoAreaActionPerformed(evt);
            }
        });

        TextoCodigoClasificacion.setBackground(new java.awt.Color(204, 204, 204));
        TextoCodigoClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCodigoClasificacionActionPerformed(evt);
            }
        });

        BotonActualizarPrecioDeLaCompra.setText("Actualiza precio de compra");
        BotonActualizarPrecioDeLaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarPrecioDeLaCompraActionPerformed(evt);
            }
        });

        BotonActualizarPrecioDeVenta.setText("Actualizar precio de venta");
        BotonActualizarPrecioDeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarPrecioDeVentaActionPerformed(evt);
            }
        });

        BotonActualizarExistencias.setText("Actualizar existencias");
        BotonActualizarExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarExistenciasActionPerformed(evt);
            }
        });

        BotonEliminarProductoDelInventario
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/peligroMasCh.png"))); // NOI18N
        BotonEliminarProductoDelInventario.setText("Eliminar producto del inventario");
        BotonEliminarProductoDelInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarProductoDelInventarioActionPerformed(evt);
            }
        });

        BotonRegresarAPantallaPrincipal.setText("Regresar a pantalla principal");
        BotonRegresarAPantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarAPantallaPrincipalActionPerformed(evt);
            }
        });

        textoDescripcionProducto.setColumns(20);
        textoDescripcionProducto.setRows(5);
        jScrollPane1.setViewportView(textoDescripcionProducto);

        jLabel9.setText("Descripcion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonRegresarAPantallaPrincipal)
                                .addGap(19, 19, 19))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(135, 135, 135)
                                                .addComponent(jLabel7))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(TextoExistencias,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 72,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(TextoCompra,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 56,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(TextoVenta,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(TextoCodigo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 106,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(BotonBuscar,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(BotonEliminarProductoDelInventario)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jLabel4)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                                TextoClasificacion))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jLabel3)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(TextoArea))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jLabel2)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(TextoProducto,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                143,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(TextoCodigoProducto)
                                                                                .addComponent(TextoCodigoArea)
                                                                                .addComponent(
                                                                                        TextoCodigoClasificacion)))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(BotonActualizarPrecioDeLaCompra,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(BotonActualizarExistencias,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(BotonActualizarPrecioDeVenta,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addGap(29, 29, 29)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BotonBuscar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(TextoProducto,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(TextoCodigoProducto,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(TextoArea,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(TextoCodigoArea,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(TextoClasificacion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(TextoCodigoClasificacion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel7)
                                                                .addGap(12, 12, 12)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(TextoCompra,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(TextoVenta,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(23, 23, 23)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel8)
                                                                        .addComponent(TextoExistencias,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(BotonActualizarPrecioDeLaCompra)
                                                                .addGap(11, 11, 11)
                                                                .addComponent(BotonActualizarPrecioDeVenta)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(BotonActualizarExistencias)))
                                                .addGap(18, 18, 18)
                                                .addComponent(BotonEliminarProductoDelInventario)
                                                .addContainerGap(25, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BotonRegresarAPantallaPrincipal)
                                                .addGap(16, 16, 16)))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoAreaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextoAreaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextoAreaActionPerformed

    private void TextoCompraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextoCompraActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextoCompraActionPerformed

    private void TextoVentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextoVentaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextoVentaActionPerformed

    private void TextoExistenciasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextoExistenciasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextoExistenciasActionPerformed

    private void TextoCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextoCodigoProductoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextoCodigoProductoActionPerformed

    private void TextoCodigoAreaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextoCodigoAreaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextoCodigoAreaActionPerformed

    private void TextoCodigoClasificacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextoCodigoClasificacionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextoCodigoClasificacionActionPerformed

    private void BotonActualizarPrecioDeLaCompraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonActualizarPrecioDeLaCompraActionPerformed

    }// GEN-LAST:event_BotonActualizarPrecioDeLaCompraActionPerformed

    private void BotonActualizarPrecioDeVentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonActualizarPrecioDeVentaActionPerformed

    }// GEN-LAST:event_BotonActualizarPrecioDeVentaActionPerformed

    private void BotonActualizarExistenciasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonActualizarExistenciasActionPerformed

    }// GEN-LAST:event_BotonActualizarExistenciasActionPerformed

    private void BotonRegresarAPantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonRegresarAPantallaPrincipalActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BotonRegresarAPantallaPrincipalActionPerformed

    private void BotonEliminarProductoDelInventarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonEliminarProductoDelInventarioActionPerformed

    }// GEN-LAST:event_BotonEliminarProductoDelInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaBuscadorInventario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaBuscadorInventario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaBuscadorInventario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaBuscadorInventario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaBuscadorInventario().setVisible(true);
            }
        });
    }

    public JButton getBotonActualizarExistencias() {
        return BotonActualizarExistencias;
    }

    public void setBotonActualizarExistencias(JButton BotonActualizarExistencias) {
        this.BotonActualizarExistencias = BotonActualizarExistencias;
    }

    public JButton getBotonActualizarPrecioDeLaCompra() {
        return BotonActualizarPrecioDeLaCompra;
    }

    public void setBotonActualizarPrecioDeLaCompra(JButton BotonActualizarPrecioDeLaCompra) {
        this.BotonActualizarPrecioDeLaCompra = BotonActualizarPrecioDeLaCompra;
    }

    public JButton getBotonActualizarPrecioDeVenta() {
        return BotonActualizarPrecioDeVenta;
    }

    public void setBotonActualizarPrecioDeVenta(JButton BotonActualizarPrecioDeVenta) {
        this.BotonActualizarPrecioDeVenta = BotonActualizarPrecioDeVenta;
    }

    public JButton getBotonBuscar() {
        return BotonBuscar;
    }

    public void setBotonBuscar(JButton BotonBuscar) {
        this.BotonBuscar = BotonBuscar;
    }

    public JButton getBotonEliminarProductoDelInventario() {
        return BotonEliminarProductoDelInventario;
    }

    public void setBotonEliminarProductoDelInventario(JButton BotonEliminarProductoDelInventario) {
        this.BotonEliminarProductoDelInventario = BotonEliminarProductoDelInventario;
    }

    public JButton getBotonRegresarAPantallaPrincipal() {
        return BotonRegresarAPantallaPrincipal;
    }

    public void setBotonRegresarAPantallaPrincipal(JButton BotonRegresarAPantallaPrincipal) {
        this.BotonRegresarAPantallaPrincipal = BotonRegresarAPantallaPrincipal;
    }

    public JTextField getTextoArea() {
        return TextoArea;
    }

    public void setTextoArea(JTextField TextoArea) {
        this.TextoArea = TextoArea;
    }

    public JTextField getTextoClasificacion() {
        return TextoClasificacion;
    }

    public void setTextoClasificacion(JTextField TextoClasificacion) {
        this.TextoClasificacion = TextoClasificacion;
    }

    public JTextField getTextoCodigo() {
        return TextoCodigo;
    }

    public void setTextoCodigo(JTextField TextoCodigo) {
        this.TextoCodigo = TextoCodigo;
    }

    public JTextField getTextoCodigoArea() {
        return TextoCodigoArea;
    }

    public void setTextoCodigoArea(JTextField TextoCodigoArea) {
        this.TextoCodigoArea = TextoCodigoArea;
    }

    public JTextField getTextoCodigoClasificacion() {
        return TextoCodigoClasificacion;
    }

    public void setTextoCodigoClasificacion(JTextField TextoCodigoClasificacion) {
        this.TextoCodigoClasificacion = TextoCodigoClasificacion;
    }

    public JTextField getTextoCodigoProducto() {
        return TextoCodigoProducto;
    }

    public void setTextoCodigoProducto(JTextField TextoCodigoProducto) {
        this.TextoCodigoProducto = TextoCodigoProducto;
    }

    public JTextField getTextoCompra() {
        return TextoCompra;
    }

    public void setTextoCompra(JTextField TextoCompra) {
        this.TextoCompra = TextoCompra;
    }

    public JTextField getTextoExistencias() {
        return TextoExistencias;
    }

    public void setTextoExistencias(JTextField TextoExistencias) {
        this.TextoExistencias = TextoExistencias;
    }

    public JTextField getTextoProducto() {
        return TextoProducto;
    }

    public void setTextoProducto(JTextField TextoProducto) {
        this.TextoProducto = TextoProducto;
    }

    public JTextField getTextoVenta() {
        return TextoVenta;
    }

    public void setTextoVenta(JTextField TextoVenta) {
        this.TextoVenta = TextoVenta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarExistencias;
    private javax.swing.JButton BotonActualizarPrecioDeLaCompra;
    private javax.swing.JButton BotonActualizarPrecioDeVenta;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEliminarProductoDelInventario;
    private javax.swing.JButton BotonRegresarAPantallaPrincipal;
    private javax.swing.JTextField TextoArea;
    private javax.swing.JTextField TextoClasificacion;
    private javax.swing.JTextField TextoCodigo;
    private javax.swing.JTextField TextoCodigoArea;
    private javax.swing.JTextField TextoCodigoClasificacion;
    private javax.swing.JTextField TextoCodigoProducto;
    private javax.swing.JTextField TextoCompra;
    private javax.swing.JTextField TextoExistencias;
    private javax.swing.JTextField TextoProducto;
    private javax.swing.JTextField TextoVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textoDescripcionProducto;
    // End of variables declaration//GEN-END:variables
}
