/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author jhont
 */
public class vistaAgregarClasificacion extends javax.swing.JFrame {

    /**
     * Creates new form vistaAgregarClasificiacion
     */
    public vistaAgregarClasificacion() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboArea = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoNombreClasificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoCodigoClasificacion = new javax.swing.JTextField();
        BotonAgregarClasificacion = new javax.swing.JButton();
        botonCancelarOperacion = new javax.swing.JButton();
        botonIrAgregarProducto = new javax.swing.JButton();
        botonRegresarAPantallaPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Agregar_Clasificación");

        ComboArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        ComboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAreaActionPerformed(evt);
            }
        });

        jLabel1.setText("Área madre: ");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Código:");

        textoCodigoClasificacion.setBackground(new java.awt.Color(204, 204, 204));
        textoCodigoClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCodigoClasificacionActionPerformed(evt);
            }
        });

        BotonAgregarClasificacion.setText("Crear clasificación");

        botonCancelarOperacion.setText("Cancelar operación");

        botonIrAgregarProducto.setText("Ir a agregar producto");

        botonRegresarAPantallaPrincipal.setText("Regresar a pantalla principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(textoCodigoClasificacion,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 83,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel2)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(textoNombreClasificacion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                227,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel1)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(ComboArea,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                138,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(BotonAgregarClasificacion)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(botonCancelarOperacion)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addComponent(botonIrAgregarProducto)))
                                .addContainerGap(51, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonRegresarAPantallaPrincipal)
                                .addGap(25, 25, 25)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ComboArea, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(textoNombreClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(textoCodigoClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonAgregarClasificacion)
                                        .addComponent(botonCancelarOperacion))
                                .addGap(27, 27, 27)
                                .addComponent(botonIrAgregarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40,
                                        Short.MAX_VALUE)
                                .addComponent(botonRegresarAPantallaPrincipal)
                                .addGap(19, 19, 19)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoCodigoClasificacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textoCodigoClasificacionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textoCodigoClasificacionActionPerformed

    private void ComboAreaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ComboAreaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ComboAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAgregarClasificacion.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAgregarClasificacion.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAgregarClasificacion.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAgregarClasificacion.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAgregarClasificacion().setVisible(true);
            }
        });
    }

    public JButton getBotonAgregarClasificacion() {
        return BotonAgregarClasificacion;
    }

    public void setBotonAgregarClasificacion(JButton BotonAgregarClasificacion) {
        this.BotonAgregarClasificacion = BotonAgregarClasificacion;
    }

    public JComboBox getComboArea() {
        return ComboArea;
    }

    public void setComboArea(JComboBox ComboArea) {
        this.ComboArea = ComboArea;
    }

    public JButton getBotonCancelarOperacion() {
        return botonCancelarOperacion;
    }

    public void setBotonCancelarOperacion(JButton botonCancelarOperacion) {
        this.botonCancelarOperacion = botonCancelarOperacion;
    }

    public JButton getBotonIrAgregarProducto() {
        return botonIrAgregarProducto;
    }

    public void setBotonIrAgregarProducto(JButton botonIrAgregarProducto) {
        this.botonIrAgregarProducto = botonIrAgregarProducto;
    }

    public JButton getBotonRegresarAPantallaPrincipal() {
        return botonRegresarAPantallaPrincipal;
    }

    public void setBotonRegresarAPantallaPrincipal(JButton botonRegresarAPantallaPrincipal) {
        this.botonRegresarAPantallaPrincipal = botonRegresarAPantallaPrincipal;
    }

    public JTextField getTextoCodigoClasificacion() {
        return textoCodigoClasificacion;
    }

    public void setTextoCodigoClasificacion(JTextField testoCodigoClasificacion) {
        this.textoCodigoClasificacion = testoCodigoClasificacion;
    }

    public JTextField getTextoNombreClasificacion() {
        return textoNombreClasificacion;
    }

    public void setTextoNombreClasificacion(JTextField textoNombreClasificacion) {
        this.textoNombreClasificacion = textoNombreClasificacion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarClasificacion;
    private javax.swing.JComboBox ComboArea;
    private javax.swing.JButton botonCancelarOperacion;
    private javax.swing.JButton botonIrAgregarProducto;
    private javax.swing.JButton botonRegresarAPantallaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textoCodigoClasificacion;
    private javax.swing.JTextField textoNombreClasificacion;
    // End of variables declaration//GEN-END:variables
}
