/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jhont
 */
public class vistaAgregarArea extends javax.swing.JFrame {

    /**
     * Creates new form vistaAgregarArea
     */
    public vistaAgregarArea() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoNombreArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoCodigoArea = new javax.swing.JTextField();
        BotonCrearArea = new javax.swing.JButton();
        BotonCancelarOperacion = new javax.swing.JButton();
        BotonAgregarClasificacion = new javax.swing.JButton();
        BotonRegresarAPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Agregar_Area");

        jLabel1.setText("Nombre: ");

        textoNombreArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreAreaActionPerformed(evt);
            }
        });

        jLabel3.setText("Código:");

        textoCodigoArea.setBackground(new java.awt.Color(204, 204, 204));

        BotonCrearArea.setText("Crear área");

        BotonCancelarOperacion.setText("Cancelar operación");
        BotonCancelarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarOperacionActionPerformed(evt);
            }
        });

        BotonAgregarClasificacion.setText("Ir a agregar clasificación");
        BotonAgregarClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarClasificacionActionPerformed(evt);
            }
        });

        BotonRegresarAPrincipal.setText("Regresar a pantalla principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(BotonCrearArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonCancelarOperacion)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonAgregarClasificacion)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonRegresarAPrincipal)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrearArea)
                    .addComponent(BotonCancelarOperacion))
                .addGap(27, 27, 27)
                .addComponent(BotonAgregarClasificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(BotonRegresarAPrincipal)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNombreAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreAreaActionPerformed

    private void BotonCancelarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCancelarOperacionActionPerformed

    private void BotonAgregarClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarClasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarClasificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAgregarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAgregarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAgregarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAgregarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAgregarArea().setVisible(true);
            }
        });
    }

    public JButton getBotonAgregarClasificacion() {
        return BotonAgregarClasificacion;
    }

    public void setBotonAgregarClasificacion(JButton BotonAgregarClasificacion) {
        this.BotonAgregarClasificacion = BotonAgregarClasificacion;
    }

    public JButton getBotonCancelarOperacion() {
        return BotonCancelarOperacion;
    }

    public void setBotonCancelarOperacion(JButton BotonCancelarOperacion) {
        this.BotonCancelarOperacion = BotonCancelarOperacion;
    }

    public JButton getBotonCrearArea() {
        return BotonCrearArea;
    }

    public void setBotonCrearArea(JButton BotonCrearArea) {
        this.BotonCrearArea = BotonCrearArea;
    }

    public JButton getBotonRegresarAPrincipal() {
        return BotonRegresarAPrincipal;
    }

    public void setBotonRegresarAPrincipal(JButton BotonRegresarAPrincipal) {
        this.BotonRegresarAPrincipal = BotonRegresarAPrincipal;
    }

    public JTextField getTextoNombreArea() {
        return textoNombreArea;
    }

    public void setTextoNombreArea(JTextField textoNombreArea) {
        this.textoNombreArea = textoNombreArea;
    }

    public JTextField getTextoCodigoArea() {
        return textoCodigoArea;
    }

    public void setTextoCodigoArea(JTextField textoCodigoArea) {
        this.textoCodigoArea = textoCodigoArea;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarClasificacion;
    private javax.swing.JButton BotonCancelarOperacion;
    private javax.swing.JButton BotonCrearArea;
    private javax.swing.JButton BotonRegresarAPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textoCodigoArea;
    private javax.swing.JTextField textoNombreArea;
    // End of variables declaration//GEN-END:variables
}
