/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhont
 */
public class vistaCarrito extends javax.swing.JFrame {
    public DefaultTableModel modelo;

    /**
     * Creates new form vistaCarrito
     */
    public vistaCarrito() {
        initComponents();
        setLocationRelativeTo(null);
        modelo=new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Subtotal");
        this.TablaCarro.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarProducto = new javax.swing.JButton();
        QuitarProducto = new javax.swing.JButton();
        RealizarVenta = new javax.swing.JButton();
        CancelarCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCarro = new javax.swing.JTable();
        LimiarCarrito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Carrito_De_Ventas");

        AgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/plus.png"))); // NOI18N
        AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoActionPerformed(evt);
            }
        });

        QuitarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/resta.png"))); // NOI18N
        QuitarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarProductoActionPerformed(evt);
            }
        });

        RealizarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/AgregarACarrito.png"))); // NOI18N
        RealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarVentaActionPerformed(evt);
            }
        });

        CancelarCompra.setText("Cancelar compra");
        CancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCompraActionPerformed(evt);
            }
        });

        jLabel1.setText("Total:");

        TablaCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaCarro);

        LimiarCarrito.setText("Limpiar carrito");
        LimiarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimiarCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LimiarCarrito)
                        .addGap(43, 43, 43)
                        .addComponent(CancelarCompra)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AgregarProducto)
                    .addComponent(QuitarProducto)
                    .addComponent(RealizarVenta))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(AgregarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(QuitarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(RealizarVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimiarCarrito)
                    .addComponent(CancelarCompra))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarProductoActionPerformed

    private void QuitarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuitarProductoActionPerformed

    private void RealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RealizarVentaActionPerformed

    private void LimiarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimiarCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LimiarCarritoActionPerformed

    private void CancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarCompraActionPerformed

    public JButton getAgregarProducto() {
        return AgregarProducto;
    }

    public JButton getCancelarCompra() {
        return CancelarCompra;
    }

    public JButton getLimiarCarrito() {
        return LimiarCarrito;
    }

    public JButton getQuitarProducto() {
        return QuitarProducto;
    }

    public JButton getRealizarVenta() {
        return RealizarVenta;
    }

    public JTable getTablaCarro() {
        return TablaCarro;
    }

    public JTextField gettxtTotal() {
        return txtTotal;
    }

    public void setAgregarProducto(JButton AgregarProducto) {
        this.AgregarProducto = AgregarProducto;
    }

    public void setCancelarCompra(JButton CancelarCompra) {
        this.CancelarCompra = CancelarCompra;
    }

    public void setLimiarCarrito(JButton LimiarCarrito) {
        this.LimiarCarrito = LimiarCarrito;
    }

    public void setQuitarProducto(JButton QuitarProducto) {
        this.QuitarProducto = QuitarProducto;
    }

    public void setRealizarVenta(JButton RealizarVenta) {
        this.RealizarVenta = RealizarVenta;
    }

    public void setjTable1(JTable jTable1) {
        this.TablaCarro = jTable1;
    }

    public void settxtTotal(JTextField jTextField1) {
        this.txtTotal = jTextField1;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCarrito().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarProducto;
    private javax.swing.JButton CancelarCompra;
    private javax.swing.JButton LimiarCarrito;
    private javax.swing.JButton QuitarProducto;
    private javax.swing.JButton RealizarVenta;
    private javax.swing.JTable TablaCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
