/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jhont
 */
public class vistaActualizarSaldo extends javax.swing.JFrame {

    /**
     * Creates new form vistaActualizarSaldo
     */
    public vistaActualizarSaldo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoSaldoActual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoModificacion = new javax.swing.JTextField();
        BotonAgregarSaldo = new javax.swing.JButton();
        BotonRetirarSaldo = new javax.swing.JButton();
        BotonVaciarCuenta = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Modificar_Saldo");

        jLabel1.setText("Saldo actual: ");

        textoSaldoActual.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Modificación:");

        BotonAgregarSaldo.setText("Agregar saldo");
        BotonAgregarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarSaldoActionPerformed(evt);
            }
        });

        BotonRetirarSaldo.setText("Retirar saldo");

        BotonVaciarCuenta.setText("Vaciar cuenta");

        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoModificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(textoSaldoActual)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(BotonAgregarSaldo)
                        .addGap(18, 18, 18)
                        .addComponent(BotonRetirarSaldo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(BotonRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(BotonVaciarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BotonAgregarSaldo)
                    .addComponent(BotonRetirarSaldo))
                .addGap(18, 18, 18)
                .addComponent(BotonVaciarCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(BotonRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarSaldoActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaActualizarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaActualizarSaldo().setVisible(true);
            }
        });
    }

    public JButton getBotonAgregarSaldo() {
        return BotonAgregarSaldo;
    }

    public void setBotonAgregarSaldo(JButton BotonAgregarSaldo) {
        this.BotonAgregarSaldo = BotonAgregarSaldo;
    }

    public JButton getBotonRegresar() {
        return BotonRegresar;
    }

    public void setBotonRegresar(JButton BotonRegresar) {
        this.BotonRegresar = BotonRegresar;
    }

    public JButton getBotonRetirarSaldo() {
        return BotonRetirarSaldo;
    }

    public void setBotonRetirarSaldo(JButton BotonRetirarSaldo) {
        this.BotonRetirarSaldo = BotonRetirarSaldo;
    }

    public JButton getBotonVaciarCuenta() {
        return BotonVaciarCuenta;
    }

    public void setBotonVaciarCuenta(JButton BotonVaciarCuenta) {
        this.BotonVaciarCuenta = BotonVaciarCuenta;
    }

    public JTextField getTextoModificacion() {
        return textoModificacion;
    }

    public void setTextoModificacion(JTextField textoModificacion) {
        this.textoModificacion = textoModificacion;
    }

    public JTextField getTextoSaldoActual() {
        return textoSaldoActual;
    }

    public void setTextoSaldoActual(JTextField textoSaldoActual) {
        this.textoSaldoActual = textoSaldoActual;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarSaldo;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JButton BotonRetirarSaldo;
    private javax.swing.JButton BotonVaciarCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textoModificacion;
    private javax.swing.JTextField textoSaldoActual;
    // End of variables declaration//GEN-END:variables
}
